"""Summarization Programs.

Phases 3 and 5 of the cross-module summarization / classification plan
land seven Programs here:

- :class:`AbstractiveSummary` — single-shot abstractive summary, plain
  string output.
- :class:`ExtractiveSummary` — no-LLM extractive summary wrapping a
  :class:`Ranker` (canonical implementation:
  ``kaos_nlp_transformers.extraction.ExtractiveRanker``); the §6.1
  Phase-5 deliverable that landed alongside ``ExtractiveRanker``.
- :class:`StructuredSummary` — schema-driven abstractive summary; the
  output payload is an arbitrary Pydantic model supplied by the
  caller.
- :class:`CitedSummary` — abstractive summary wrapped in the existing
  :class:`~kaos_llm_core.signatures.grounding.Answer` /
  :class:`~kaos_llm_core.signatures.grounding.GroundedAnswer` types so
  every claim carries verifiable spans back to source.
- :class:`MapReduceSummary` — long-doc summarizer that chunks, summarizes
  each chunk concurrently, then merges via
  :class:`~kaos_llm_core.composition.MapReduce`.
- :class:`RefineSummary` — long-doc summarizer that walks chunks
  left-to-right, maintaining a running summary
  via :class:`~kaos_llm_core.composition.reduce.Refine`.
- :class:`HierarchicalSummary` — long-doc summarizer using
  :class:`~kaos_llm_core.composition.Tree`.

All Programs share the same wiring:

1. A ``Signature`` declares the LLM contract.
2. A :class:`~kaos_llm_core.programs.call.Call` (or
   :class:`AbstractiveSummary` for nested cases) does the LLM work.
3. ``forward()`` wraps the typed call output in a
   :class:`~kaos_llm_core.results.Summary`.

Routing, caching, batching, observability, retries, cost reporting,
and budget enforcement are provided by the base
:class:`~kaos_llm_core.programs.call.Call` and
:class:`~kaos_llm_core.programs.base.Program` infrastructure.

.. warning::
   Summaries produced by these Programs are **statistical
   approximations** generated by upstream LLM providers. They may
   hallucinate, omit material facts, paraphrase inaccurately, or
   misquote source documents. Do not rely on summary text for
   legal, financial, medical, compliance, or regulatory decisions
   without human expert review. The :class:`CitedSummary` Program
   runtime-verifies quoted spans against the source — but
   verification only proves the quote exists in the source, not
   that the surrounding paraphrase is faithful. See
   :doc:`/README` for the package-level data-handling note.
"""

from __future__ import annotations

from kaos_llm_core.programs.summarize.abstractive import (
    AbstractiveSummary,
    AbstractiveSummarySignature,
    CitedSummary,
)
from kaos_llm_core.programs.summarize.clustered import ClusteredSummary
from kaos_llm_core.programs.summarize.extractive import (
    ExtractiveSummary,
    RankedSegment,
    Ranker,
)
from kaos_llm_core.programs.summarize.hybrid import HybridSummary
from kaos_llm_core.programs.summarize.long_doc import (
    HierarchicalSummary,
    MapReduceSummary,
    RefineSummary,
)
from kaos_llm_core.programs.summarize.query_focused import QueryFocusedSummary
from kaos_llm_core.programs.summarize.structured import StructuredSummary

__all__ = [
    "AbstractiveSummary",
    "AbstractiveSummarySignature",
    "CitedSummary",
    "ClusteredSummary",
    "ExtractiveSummary",
    "HierarchicalSummary",
    "HybridSummary",
    "MapReduceSummary",
    "QueryFocusedSummary",
    "RankedSegment",
    "Ranker",
    "RefineSummary",
    "StructuredSummary",
]
