"""Evidence-Driven Refine — produce → critique → refine for factual answers.

The canonical "answer cites a tool result" pattern at the kaos-llm-core
layer. Mirrors what kaos-agents' ``AgenticLoop`` + ``GoalChecker``
achieve at the agent layer, but with the discipline expressed as a
single ``Refine`` composition. Future readers facing the question
"how do I make the model cite its sources?" should land here for the
canonical Program-level answer.

The pattern, in words:

  1. A *producer* Call sketches an answer to a factual question given
     a block of tool-result text. The producer is intentionally not
     told it MUST cite — that's the critic's job.
  2. A *judge* (``Judge`` with a citation-focused criteria string)
     scores the answer on a 0..1 scale.
  3. A *Refine* loop wraps the producer with the judge. When the
     judge's ``quality_score`` falls below ``min_score``, Refine
     clones the producer with the judge's ``reasoning`` injected as
     an extra instruction ("Your previous answer ... Search the
     evidence and cite the source before answering.") and re-runs.
  4. The loop terminates on the first pass that hits ``min_score``,
     or after ``max_iterations`` returning the best output seen.

The same pattern composes upstream: in the kaos-agents AgenticLoop,
the planner Signature picks tool groups, the worker invokes ReAct
(which calls real tools), the GoalChecker critic emits
``needs_more_work``/``satisfied`` verdicts, and the loop threads the
critic's ``next_action`` to the next worker iteration. Refine is the
single-Call-with-fixed-evidence reduction of that.

This example is offline by default: ``tool_results`` is a static
block of fact-bearing text passed as input, not a live tool call. To
see the Refine retry loop actually fire, the answer must be
generated by a model that can be prompted to omit citations on the
first pass — Haiku is reliable for that. The judge runs on a
stronger model (Sonnet) so its scoring is stable.

Usage::

    uv run python -m examples.evidence_driven_refine
    uv run python -m examples.evidence_driven_refine --provider anthropic --json
    uv run python -m examples.evidence_driven_refine --min-score 0.9 --max-iterations 4
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
from typing import Any

from examples.models import get_preset
from kaos_llm_core import (
    Call,
    InputField,
    Judge,
    OutputField,
    Refine,
    Signature,
)

# --- Signatures ---


class FactualAnswer(Signature):
    """Answer a factual question, citing sources from the evidence block.

    The evidence block is a verbatim copy of one or more tool results
    (for example, a Federal Register search hit or a web fetch). A
    *correct* answer quotes or paraphrases a specific evidence span
    and identifies its source by URL or document title. An answer
    that asserts a fact not visible in the evidence block is wrong
    even if it happens to be true — this signature is the contract
    that the model uses the supplied evidence rather than its own
    prior.
    """

    question: str = InputField(description="The user's factual question.")
    evidence: str = InputField(
        description=(
            "Verbatim tool results — newline-separated hits, each "
            "carrying its own source URL or title. The model must "
            "ground its answer in one or more of these hits."
        )
    )
    answer: str = OutputField(
        description=(
            "One- or two-sentence answer to the question. Cite the "
            "source URL or title inline using brackets, e.g. "
            "'[https://example.com/rule]' or '[90 FR 12345]'."
        )
    )
    cited_sources: list[str] = OutputField(
        description=(
            "Every source URL or title cited in ``answer``. Empty "
            "list when the model declined to cite — the judge below "
            "uses this to score the response."
        )
    )


# --- Fixture ---


EVIDENCE_BLOCK = """\
[https://www.federalregister.gov/documents/2026/05/10/2026-09876]
USDA Agricultural Marketing Service — final rule, "Federal Milk
Marketing Order Reform", 90 FR 12345 (May 10, 2026). Adjusts Class I
fluid milk pricing formulas effective August 1, 2026. Public comment
period closed February 2026.

[https://www.federalregister.gov/documents/2026/04/22/2026-08410]
Food and Drug Administration — proposed rule, "Yogurt Standards of
Identity Amendment", 91 FR 8410 (Apr. 22, 2026). Would reduce
minimum protein content from 3.25% to 2.75%.

[https://www.federalregister.gov/documents/2026/03/14/2026-05123]
USDA Food Safety and Inspection Service — interim final rule,
"Dairy Plant Sanitation Recordkeeping", 91 FR 5123 (Mar. 14, 2026).
Extends electronic recordkeeping mandate to small dairy plants.
"""


# --- Refine composition ---


def build_refine(provider: str | None, *, max_iterations: int, min_score: float) -> Refine:
    """Wire the producer + judge into a Refine.

    The producer Call uses the cheap model — it gets called on every
    iteration and we want refinement to be affordable. The judge
    uses the balanced/stronger model so its scores are stable
    enough to drive the early-stop decision.
    """
    preset = get_preset(provider)
    producer = Call(FactualAnswer, model=preset.cheap)
    judge = Judge(
        FactualAnswer,
        producer_model=preset.cheap,
        judge_model=preset.balanced,
        criteria=(
            "The answer cites at least one URL or document title from "
            "the supplied evidence block in inline brackets (e.g. "
            "'[https://...]' or '[90 FR 12345]'), AND the cited "
            "source actually appears in the evidence. Score 1.0 for "
            "a well-cited answer grounded in the evidence; score 0.0 "
            "for an answer with no citation or a citation that does "
            "not appear in the evidence; partial credit for a "
            "citation that appears but is the wrong source for the "
            "asserted fact."
        ),
    )
    return Refine(
        producer,
        judge,
        max_iterations=max_iterations,
        min_score=min_score,
    )


# --- Local-only echo ("did the answer cite anything from the evidence?") ---


_URL_OR_FR_CITE_PATTERN = re.compile(r"\[(https?://[^\]]+|\d+\s+FR\s+\d+)\]")


def local_citation_count(answer: str, evidence: str) -> int:
    """Count how many distinct bracketed citations in ``answer`` also
    appear in ``evidence``. This is the *deterministic* version of
    what the judge is asked to estimate stochastically — useful for
    eyeballing whether the Refine loop did the right thing, since
    LLM-judge scores can swing 20-40 points across re-runs.
    """
    cited = {m.group(1) for m in _URL_OR_FR_CITE_PATTERN.finditer(answer)}
    return sum(1 for c in cited if c in evidence)


# --- Runner ---


async def run(
    *,
    question: str,
    provider: str | None,
    max_iterations: int,
    min_score: float,
    json_output: bool,
) -> dict[str, Any]:
    refine = build_refine(provider, max_iterations=max_iterations, min_score=min_score)
    result = await refine(question=question, evidence=EVIDENCE_BLOCK)

    summary: dict[str, Any] = {
        "question": question,
        "answer": result.answer,
        "cited_sources": list(result.cited_sources),
        "iterations": result.iterations,
        "final_score": result.final_score,
        "stop_reason": str(result.stop_reason),
        "local_grounded_citations": local_citation_count(result.answer, EVIDENCE_BLOCK),
    }

    if json_output:
        print(json.dumps(summary, indent=2, default=str))
    else:
        print(f"Question: {question}")
        print(f"Provider: {provider or 'anthropic'}")
        print(f"Stop reason: {summary['stop_reason']} after {summary['iterations']} iteration(s)")
        print(f"Final judge score: {summary['final_score']:.2f}")
        print(f"Grounded citations (local check): {summary['local_grounded_citations']}")
        print()
        print("Answer:")
        print(result.answer)
        if result.cited_sources:
            print()
            print("Cited sources:")
            for src in result.cited_sources:
                print(f"  - {src}")

    return summary


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Evidence-driven Refine — produce → judge → refine "
            "until the answer cites a tool result."
        ),
    )
    parser.add_argument(
        "--question",
        default=(
            "What is the effective date of the Class I fluid milk "
            "pricing reform under the recent USDA AMS final rule?"
        ),
        help="Question to answer.",
    )
    parser.add_argument(
        "--provider",
        choices=["anthropic", "openai", "google"],
        default=None,
        help="LLM provider (default: anthropic).",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=3,
        help="Max Refine iterations.",
    )
    parser.add_argument(
        "--min-score",
        type=float,
        default=0.8,
        help="Judge quality threshold for early-stop in [0.0, 1.0].",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Emit JSON instead of human-readable output.",
    )
    args = parser.parse_args()

    asyncio.run(
        run(
            question=args.question,
            provider=args.provider,
            max_iterations=args.max_iterations,
            min_score=args.min_score,
            json_output=args.json_output,
        )
    )


if __name__ == "__main__":
    main()
